[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "max-age=604800, must-revalidate"
        Referrer-Policy = "no-referrer"
        Expect-CT = "enforce, max-age=3155760000"
        X-Content-Type-Options = "nosniff"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
        '''
       
        Permissions-Policy = '''
            interest-cohort=(none)
        '''

        Content-Security-Policy = '''
            default-src 'none';
            script-src 'nonce-d2h5LXlvdS1kZWNvZGUtdGhpcw==' 'report-sample';
            style-src 'nonce-c3Vzc3ktYmFrLWNoZWVzZWJ1cmdlcg==' 'nonce-am9lLW1hbWEtc3Vzc3ktYmFrYQ==' 'strict-dynamic';
            img-src https:;
            font-src 'nonce-c3Vzc3ktYmFrLWNoZWVzZWJ1cmdlcg==';
            manifest-src 'none';
            media-src 'none';
            object-src 'none';
            frame-src 'none';
            frame-ancestors 'none';
            worker-src 'none';
            child-src 'none';
            base-uri 'none';
            upgrade-insecure-requests;
            require-trusted-types-for 'script';
        '''
