[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "no-cache"
        Referrer-Policy = "no-referrer"
        Expect-CT = "enforce, max-age=3155760000"
        X-Content-Type-Options = "nosniff"
       
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
        '''
       
        Permissions-Policy = '''
            interest-cohort=(none)
        '''
